execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 1m30s
  scenario: simple

scenarios:
  simple:
    requests:
         - http://dayrhecdad008.enterprisenet.org:8091/gsrsourcesystemservice/charmaintenance/ruleaction
reporting:
- module: final-stats
  dump-xml: stats.xml 
